CREATE DATABASE Std_DB;

USE Std_DB;

CREATE TABLE Std_Register (
    F_Name VARCHAR(20) NOT NULL,
    L_Name VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL PRIMARY KEY,
    Password VARCHAR(20) NOT NULL
);
